### ISSUE TITLE
Aurora from Canary release has non-functional settings.

### ISSUE THREAD

**Issue by CodingWithAnxiety** [bijju089/aurora-theme#5]
### Aurora from Canary release has non-functional settings.
Hello! I am making filing this **issue** for both the [Main Branch](https://github.com/cxstudios-llc/aurora-theme/tree/main) and the release tag [v1.0-2](https://github.com/cxstudios-llc/aurora-theme/tree/v1.0-2). In these releases, specifically since [this commit](https://github.com/cxstudios-llc/aurora-theme/commit/c8b0273da0bc4c0845c66e0f1be86da72b55de32), settings EXCEPT FOR DARK MODE cannot be changed, and revert to their default values when the "Submit" button is pressed. View attached gif.

![firefox_bSNpW00Cp8](https://github.com/user-attachments/assets/ab64df28-f4a8-4458-9a04-21c27c0f6b23)

#### Expected behavior
When a setting is changed and the submit button is pressed, the setting is expected to change and remain in that modified state.

#### What actually happens 
All settings, except for the "Dark Mode" setting, revert back to their default setting once the "Submit" button is pressed, meaning that the settings for Aurora cannot be modified.

**Comment by bijju089** [comment]
Hello, I'm aware of this issue. I was busy with other projects. Now I am back on Aurora, and I'll post update very soon!
Thanks for showing your interest in our projects

**Comment by CodingWithAnxiety** [comment]
I'm going to sit down later this week and see if I can't figure out why these settings now fail to save. I'll make a push once I figure out what causes the regression.

**Comment by bijju089** [comment]
sure, that would be helpful

**Comment by bijju089** [comment]
Thank you. The bug has been fixed in https://github.com/bijju089/aurora-theme/commit/7bfcbe76df638c8c8aeb6f27746956dda1a2c86b
